### PR TITLE
Docker + direct IMDB / TVDB search

### PR DESCRIPTION
**Pull request by clementduveau**
As I am not really confortable playing around all the venv in python nor do I have it in my servers, I wanted to use Docker to do it.

Docker is a pretty popular option in the community. So I created a simple Dockerfile and added some instructions on how to use it without a published image.

### CODE REVIEW

**Comment by clementduveau** [comment]
I added another commit that change how lookup works. I belive that using plex.agent is not the way to go. We should use IMDB and TVDB references as they are the common source of id. Therefore, I change the extract provider method to use guids given by plex (disregarding the plex agents used).

The Docker option is of course not affected. Feel free to just keep that if you want to.

Edit: Should fix all the no matches bugs

**Comment by wilmardo** [comment]
Awesome! Thanks for the contribution!
Nice to know that my hacky script is still of use to people :)

I am currently busy at work but I will take a look at the changes hopefully in the new year. Polishing up this repo has been on my TODO list for some time. This PR gives me new motivation to get to it, so thanks for that too.

**Comment by wilmardo** [comment]
I choose to go with the matching on paths as proposed in this PR:
https://github.com/wilmardo/migrate-plex-to-jellyfin/pull/24

I will however cherrypick you docker commit, very useful addition <3

**Comment by wilmardo** [comment]
Cherry-picked in:
https://github.com/wilmardo/migrate-plex-to-jellyfin/commit/13731a9b7a1e5ed6d158b37ed2ed85333a7fd6e2

Thanks again!

**Pull request closed without merging**
